---
 ENV: demo
 application: demo-app
 server_role: web
 web_instance_type: t2.micro

 web_security_groups:
   - sg_name: web-sg
     sg_description: This sg is for app instance
     sg_rules:
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 8080
         to_port: 8080
         cidr_ip: 0.0.0.0/0
 linux_distribution: ubuntu
 ubuntu_release: trusty
 ami_store: ebs
 virutalization_type: hvm
 cpu_architecture: amd64
