---
 - hosts: local
   connection: local
   gather_facts: no
   vars_files:
     - vars/vpc.yml
     - vars/ec2_key.yml
     - vars/rds.yml
     - vars/webserver.yml
     - vars/elb.yml
   tasks:
     - include: tasks/vpc.yml
     - include: tasks/ec2_key.yml
     - include: tasks/webserver.yml
     - include: tasks/rds.yml
     - include: tasks/elb.yml
